name: GitHub Actions Build UAS-PCC-ROGER-2025
run-name: ${{ github.actor }} is Building Docker Image 🚀
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Verify Dockerfile exists
        run: ls -la

      - name: login and build
        run: |
          docker build -t roger375/uas-pcc-bintang_rogerman-2025:latest -f Dockerfile .
          echo ${{ secrets.DOCKERHUB_ACCESSTOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push roger375/uas-pcc-bintang_rogerman-2025:latest
